#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 19 16:52:18 2018

@author: ms1409
"""
import numpy as np 

def TotalVar(phiOld, c, nt):
    "finding the total variation of each scheme, plotted against time"
    
    nx = len(phiOld)
    
    TotalVarFTBS = np.zeros(nx)
    TotalVarFTBS_sum = np.zeros(nt-2)
    
    for i in range(2,nt):
        
    
    